### ISSUE TITLE
"Border and Fill" submenu cutting off text under windows 

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#117]
I tested only on Windows 10 at that time. Ksnip version 1.7.1
The "Border and Fill" submenu is cutting out the translated word.
Does not have automatic size adjustment

<a href="https://imgbb.com/"><img src="https://i.ibb.co/TcCPPLS/anotador5.jpg" alt="anotador5" border="0"></a>

**Comment by DamirPorobic** [comment]
It actually has auto size adjustment, even some additional offset but for some reason Qt seems to be failing to calculate the size.

**Comment by DamirPorobic** [comment]
I've pushed a small change, added some offset, give it a try.

**Comment by antrrax** [comment]
It was still not enough, after the change was like this:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/V9wL11q/anotador001.jpg" alt="anotador001" border="0"></a>

**Comment by DamirPorobic** [comment]
Added a bit more, can you test again?

**Comment by antrrax** [comment]
The continuous version currently available on github is two days ago. There must have been a problem sending this new change

**Comment by DamirPorobic** [comment]
No, actually the change is from Friday but it looks like I forgot to click send on my comment so I wrote it again this morning.

**Comment by antrrax** [comment]
at the moment it is like this in Windows 10
<a href="https://imgbb.com/"><img src="https://i.ibb.co/RYgfPmt/teste.jpg" alt="teste" border="0"></a>

**Comment by DamirPorobic** [comment]
Ok, this is the latest?

**Comment by antrrax** [comment]
yes I usually test the latest continuous version

**Comment by DamirPorobic** [comment]
Give it another try.

**Comment by antrrax** [comment]
I tested version 1.7.1 that is available on github released yesterday. And there was no change
I'm testing on Windows 10

**Comment by DamirPorobic** [comment]
Oh, wait, I‘ve only pushed my change of kimageannotator, that will not cause a new ksnip build.  Let me fix that.

________________________________

**Comment by DamirPorobic** [comment]
Ok, building now.

**Comment by antrrax** [comment]
I tested on Windows 10 and decreased the submenu instead of increasing it.
compare to previous images
<a href="https://imgbb.com/"><img src="https://i.ibb.co/GWN92Xs/erro.jpg" alt="erro" border="0"></a>

**Comment by DamirPorobic** [comment]
Seems to be a windows only issue. The texts seems to be correct under linux.

**Comment by antrrax** [comment]
It really seems to be a Windows 10 problem only
On Linux mint 19.3 x64 Cinnamon X11 is working correctly

**Comment by DamirPorobic** [comment]
Seems to be not even translation related, the English text is cut off too.

**Comment by DamirPorobic** [comment]
Give it another try.

**Comment by DamirPorobic** [comment]
Should be fixed now, testen with Portuguese language on ma Windows machine and seems to be working.
