### ISSUE TITLE
Vertical scrollbar missing after using Paste embedded and moving the image

### ISSUE THREAD

**Issue by ljubadr** [ksnip/kImageAnnotator#232]
**Describe the bug**

When I use `Edit -> Paste embedded` with tall screenshots and I move the new screenshot I don't see vertical scroll

**To Reproduce**

1. Take screenshot
2. Take another screenshot that's tall
3. Copy the second screenshot into clipboard
4. Go to the first screenshot
5. Edit -> Paste embedded
6. Move the second image below the first image

**Actual behavior**

Vertical scrollbar is not visible

**Expected behavior**

Vertical scrollbar is visible

**Screenshots**

For the screenshot example I've combined 2 screenshots: image from the [readme](https://github.com/ksnip/ksnip) and screenshot of readme [Features](https://github.com/ksnip/ksnip#features) section

Here is ksnip at 100% zoom. 

![image](https://user-images.githubusercontent.com/13367907/116127555-fa9f1680-a695-11eb-8300-59e092bf86b1.png)

ksnip at 30% zoom. This is the only way to annotate second image

![image](https://user-images.githubusercontent.com/13367907/116127569-fecb3400-a695-11eb-9b65-f84f481183e2.png)

Modify canvas behavior - no vertical scroll. It's not possible to edit bottom canvas line. But bottom line is correct and canvas includes both images. If I save the image it's saved to include both images as well.

![image](https://user-images.githubusercontent.com/13367907/116127584-025ebb00-a696-11eb-9392-3377f96b516f.png)

**Desktop**

 - OS: Linux
 - Ubuntu 20.04
 - GNOME Shell 3.36.7
 - ksnip version 1.9.0
 - `snap install ksnip --edge`

Copied from ksnip

```
Version: 1.9.0
Build: 

Using:
Qt5
X11
KDE Wayland
Gnome Wayland
```

**Comment by DamirPorobic** [comment]
@ljubadr This should be fixed now, can you test again?

**Comment by ljubadr** [comment]
Hi @DamirPorobic,

I've tested with the snap edge version that I have installed and it's up to date. I've had it installed with `sudo snap install ksnip --edge`. In this version I can still reproduce the error. I also did `sudo snap refresh ksnip` but there were no updates available... Help -> About -> Version shows this

![image](https://user-images.githubusercontent.com/13367907/118382883-9c47c280-b5c7-11eb-96d7-87fc72486c1a.png)

After that I downloaded the `.deb` file from the [Continuous build release page](https://github.com/ksnip/ksnip/releases/tag/continuous) and I've tested that version. I see that the bug is fixed and that the scroll bars now work. Awesome, thanks again for the fast response :+1: 

Question about the snap edge version - should I use this to test bugfixes or should I download deb file and test that?
